services:
  server:
    build: ./app
    container_name: chat-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # volumes:
    #   - /app:/chat-app
    ports:
      - 80:80
    environment:
      - DATABASE_USERNAME=myusername
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOSTNAME=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
    depends_on:
      - db
  db:
    container_name: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data/
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgresql
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80
    depends_on:
      - server

volumes:
  db_data: